version: '3.8'

services:
  backend:
    build: ./backend
    container_name: resmern-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_TOKEN=${JWT_TOKEN}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    volumes:
      - ./uploads:/app/uploads
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - nlp-service
      - latex-service
    networks:
      - app-network

  nlp-service:
    build: ./nlp
    container_name: resmern-nlp
    ports:
      - "8001:8001"
    volumes:
      - ./nlp:/app
    networks:
      - app-network

  latex-service:
    build: ./latexParsing
    container_name: resmern-latex
    ports:
      - "8002:8002"
    volumes:
      - ./latexParsing:/app
      - ./latexParsing/output:/app/output
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  uploads:
  latex-output:
